import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JFrame;


public class account extends javax.swing.JFrame {
    private CardLayout cardLayout;

    /**
     * Creates new form account
     */
    public account() {
        initComponents();
        setupFrameChangeButtons();
        setupLogoutButton();
          // Assuming cardManager is already declared and initialized by initComponents()
        cardLayout = (CardLayout) cardManager.getLayout(); // Get the CardLayout from cardManager
        
        cardManager.add(accountCard, "accountCard");
        cardManager.add(currentVehiclesCard, "currentVehiclesCard");
        cardManager.add(jPanel1, "returnsCard");

    
        setupCardChangeButtons();

        // Set 'accountCard' to be the first viewed card when the application starts
        cardLayout.show(cardManager, "accountCard"); // The string must match the name used in cardManager.add(...)
        this.setVisible(true); 

  


        // Use getInstance() to call non-static methods on SessionManager
        SessionManager sessionManager = SessionManager.getInstance();
        if (sessionManager.isLoggedIn()) {
            User currentUser = sessionManager.getCurrentUser();
            
                        // Extract user information
            int id = currentUser.getId();
            String email = currentUser.getEmail();
            String forename = currentUser.getForename();
            String surname = currentUser.getSurname();
            String address = currentUser.getAddress();
            String mobileNumber = currentUser.getMobileNumber();

            // Set text fields with user information
            emailTextField.setText(email);
            forenameTextField.setText(forename);
            surnameTextField.setText(surname);
            addressTextField.setText(address);
            mobileTextField.setText(mobileNumber);

        }
        
        
    }
    
        
        

// Method to set up action listeners for buttons responsible for switching cards
private void setupCardChangeButtons() {
    addActionListenerToCardButton(accountDetailsButton, "accountCard");
    addActionListenerToCardButton(currentVehiclesButton, "currentVehiclesCard");
    addActionListenerToCardButton(returnsButton, "returnsCard");
}

// Method to add an action listener to a button to switch to a specific card
private void addActionListenerToCardButton(JButton button, String cardName) {
    button.addActionListener(e -> switchCard(cardName));
}

private void switchCard(String cardName) {
    System.out.println("Switching to card: " + cardName); // Debug output
    cardLayout.show(cardManager, cardName);
}


    // Method to set up action listeners for buttons responsible for opening different JFrames
    private void setupFrameChangeButtons() {
        addActionListenerToButton(homeButton, userHomePage.class);
        addActionListenerToButton(carsButton, testingCarView.class);
        addActionListenerToButton(accountDetailsButton, account.class);
        addActionListenerToButton(logoutButton, login.class);
    }

    // Method to add an action listener to a button to open a specific JFrame
    private void addActionListenerToButton(JButton button, Class<? extends JFrame> frameClass) {
        button.addActionListener(e -> openFrameAndCloseCurrent(frameClass));
    }
    
    // Call this method in the constructor or initialization block to set up the logout button
    private void setupLogoutButton() {
        logoutButton.addActionListener(e -> logoutAndOpenLogin());
    }
    

    // This method will handle the logout process and switch to the login screen
    private void logoutAndOpenLogin() {
        // Logout the user
        SessionManager.getInstance().logout();


        // Close the current frame
        this.dispose();

        // Open the login screen
        JFrame loginFrame = new login();
        loginFrame.setVisible(true);
    }

    // Method to open a new JFrame and close the current one
    private void openFrameAndCloseCurrent(Class<? extends JFrame> frameClass) {
        try {
            JFrame frame = frameClass.getDeclaredConstructor().newInstance();
            frame.setVisible(true);
            this.dispose(); // Close the current frame
        } catch (Exception e) {
            e.printStackTrace();
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        navBarTop = new javax.swing.JPanel();
        accountButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        carsButton = new javax.swing.JButton();
        carServiceLabel = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        navBarSide = new javax.swing.JPanel();
        accountDetailsButton = new javax.swing.JButton();
        currentVehiclesButton = new javax.swing.JButton();
        returnsButton = new javax.swing.JButton();
        cardManager = new javax.swing.JPanel();
        accountCard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        forenameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mobileTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        surnameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        currentVehiclesCard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 100));

        navBarTop.setBackground(new java.awt.Color(153, 153, 255));
        navBarTop.setMinimumSize(new java.awt.Dimension(800, 60));

        accountButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accountButton.setText("Account");
        accountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButtonjButton6ActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonjButton7ActionPerformed(evt);
            }
        });

        carsButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        carsButton.setText("Cars");
        carsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carsButtonjButton8ActionPerformed(evt);
            }
        });

        carServiceLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        carServiceLabel.setForeground(new java.awt.Color(255, 255, 255));
        carServiceLabel.setText("CarServiceCompanion");

        homeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonjButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navBarTopLayout = new javax.swing.GroupLayout(navBarTop);
        navBarTop.setLayout(navBarTopLayout);
        navBarTopLayout.setHorizontalGroup(
            navBarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBarTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carServiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        navBarTopLayout.setVerticalGroup(
            navBarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBarTopLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(navBarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carServiceLabel)
                    .addComponent(carsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(navBarTop, java.awt.BorderLayout.NORTH);

        navBarSide.setBackground(new java.awt.Color(255, 255, 255));
        navBarSide.setPreferredSize(new java.awt.Dimension(170, 100));

        accountDetailsButton.setBackground(new java.awt.Color(153, 153, 255));
        accountDetailsButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        accountDetailsButton.setForeground(new java.awt.Color(255, 255, 255));
        accountDetailsButton.setText("Account Information");
        accountDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountDetailsButtonActionPerformed(evt);
            }
        });

        currentVehiclesButton.setBackground(new java.awt.Color(153, 153, 255));
        currentVehiclesButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        currentVehiclesButton.setForeground(new java.awt.Color(255, 255, 255));
        currentVehiclesButton.setText("Current Vehicles");

        returnsButton.setBackground(new java.awt.Color(153, 153, 255));
        returnsButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        returnsButton.setForeground(new java.awt.Color(255, 255, 255));
        returnsButton.setText("Account Status");

        javax.swing.GroupLayout navBarSideLayout = new javax.swing.GroupLayout(navBarSide);
        navBarSide.setLayout(navBarSideLayout);
        navBarSideLayout.setHorizontalGroup(
            navBarSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navBarSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentVehiclesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(accountDetailsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        navBarSideLayout.setVerticalGroup(
            navBarSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarSideLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(accountDetailsButton)
                .addGap(18, 18, 18)
                .addComponent(currentVehiclesButton)
                .addGap(18, 18, 18)
                .addComponent(returnsButton)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        getContentPane().add(navBarSide, java.awt.BorderLayout.WEST);

        cardManager.setBackground(new java.awt.Color(255, 153, 153));
        cardManager.setPreferredSize(new java.awt.Dimension(700, 453));
        cardManager.setRequestFocusEnabled(false);
        cardManager.setLayout(new java.awt.CardLayout());

        accountCard.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setText("Account Information");

        jLabel3.setText("Forename");

        jLabel4.setText("Surname");

        jLabel5.setText("Mobile Number");

        jLabel6.setText("Home Address");

        emailTextField.setText("jTextField4");

        forenameTextField.setText("jTextField4");

        jLabel7.setText("Email Address");

        mobileTextField.setText("jTextField4");

        jLabel8.setText("Password");

        surnameTextField.setText("jTextField4");

        addressTextField.setText("jTextField4");

        passwordTextField.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(forenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(mobileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(106, 106, 106)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(passwordTextField))))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout accountCardLayout = new javax.swing.GroupLayout(accountCard);
        accountCard.setLayout(accountCardLayout);
        accountCardLayout.setHorizontalGroup(
            accountCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        accountCardLayout.setVerticalGroup(
            accountCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardManager.add(accountCard, "card2");

        currentVehiclesCard.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Current Vehicles");

        javax.swing.GroupLayout currentVehiclesCardLayout = new javax.swing.GroupLayout(currentVehiclesCard);
        currentVehiclesCard.setLayout(currentVehiclesCardLayout);
        currentVehiclesCardLayout.setHorizontalGroup(
            currentVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentVehiclesCardLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        currentVehiclesCardLayout.setVerticalGroup(
            currentVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentVehiclesCardLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        cardManager.add(currentVehiclesCard, "card3");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        cardManager.add(jPanel1, "card5");

        getContentPane().add(cardManager, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carsButtonjButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carsButtonjButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carsButtonjButton8ActionPerformed

    private void logoutButtonjButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonjButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonjButton7ActionPerformed

    private void accountButtonjButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonjButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountButtonjButton6ActionPerformed

    private void accountDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountDetailsButtonActionPerformed

    private void homeButtonjButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonjButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonjButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountButton;
    private javax.swing.JPanel accountCard;
    private javax.swing.JButton accountDetailsButton;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel carServiceLabel;
    private javax.swing.JPanel cardManager;
    private javax.swing.JButton carsButton;
    private javax.swing.JButton currentVehiclesButton;
    private javax.swing.JPanel currentVehiclesCard;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField forenameTextField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField mobileTextField;
    private javax.swing.JPanel navBarSide;
    private javax.swing.JPanel navBarTop;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton returnsButton;
    private javax.swing.JTextField surnameTextField;
    // End of variables declaration//GEN-END:variables
}
