
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author D21124318
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        setupActionListeners();
        
        // Use getInstance() to call non-static methods on SessionManager
        SessionManager sessionManager = SessionManager.getInstance();
        if (sessionManager.adminLoggedIn()) {
            Admin currentAdmin = sessionManager.getCurrentAdmin();
            
                        // Extract user information
            int adminID = currentAdmin.getID();
            //String email = currentUser.getEmail();
            String adminEmail = currentAdmin.getEmail();
            

            // Set text fields with user information
            //String currentText = greetingText.getText();
            //String updatedText = currentText + adminEmail;
            //greetingText.setText(updatedText);

        }
    }

    // Method to set up action listeners for various buttons related to functionality
    private void setupActionListeners() {
        addActionListenerToButton(DashboardButton, this::openAdminHome);
        addActionListenerToButton(UsersButton, this::openManageCustomers);
        addActionListenerToButton(VehiclesButton, this::openManageVehicles);
        addActionListenerToButton(OverdueAccountsButton, this::openOverdueAccounts);

        
        
    }
    // Method to add an action listener to a button with a specific action
    private void addActionListenerToButton(JButton button, Runnable action) {
        button.addActionListener(e -> action.run());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavigationMenu = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 220), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 160));
        DashboardButton = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 140));
        UsersButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 20));
        VehiclesButton = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20));
        OverdueAccountsButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 140));
        Dashboard = new javax.swing.JPanel();
        TotalVehicles = new javax.swing.JPanel();
        TotalUsers = new javax.swing.JPanel();
        AvailableVehicles = new javax.swing.JPanel();
        OverdueAccounts = new javax.swing.JScrollPane();
        RentedVehicles = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(885, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        NavigationMenu.setBackground(new java.awt.Color(33, 116, 177));
        NavigationMenu.setLayout(new javax.swing.BoxLayout(NavigationMenu, javax.swing.BoxLayout.Y_AXIS));
        NavigationMenu.add(filler1);

        DashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_35.png"))); // NOI18N
        DashboardButton.setBorderPainted(false);
        DashboardButton.setContentAreaFilled(false);
        NavigationMenu.add(DashboardButton);
        NavigationMenu.add(filler6);

        UsersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageusers_35.png"))); // NOI18N
        UsersButton.setBorderPainted(false);
        UsersButton.setContentAreaFilled(false);
        NavigationMenu.add(UsersButton);
        NavigationMenu.add(filler4);

        VehiclesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/managevehicles_35.png"))); // NOI18N
        VehiclesButton.setBorderPainted(false);
        VehiclesButton.setContentAreaFilled(false);
        NavigationMenu.add(VehiclesButton);
        NavigationMenu.add(filler5);

        OverdueAccountsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/overdue_35.png"))); // NOI18N
        OverdueAccountsButton.setBorderPainted(false);
        OverdueAccountsButton.setContentAreaFilled(false);
        NavigationMenu.add(OverdueAccountsButton);
        NavigationMenu.add(filler2);

        getContentPane().add(NavigationMenu);
        NavigationMenu.setBounds(0, 0, 60, 520);

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setMinimumSize(new java.awt.Dimension(804, 520));
        Dashboard.setName(""); // NOI18N
        Dashboard.setPreferredSize(new java.awt.Dimension(804, 520));

        javax.swing.GroupLayout TotalVehiclesLayout = new javax.swing.GroupLayout(TotalVehicles);
        TotalVehicles.setLayout(TotalVehiclesLayout);
        TotalVehiclesLayout.setHorizontalGroup(
            TotalVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        TotalVehiclesLayout.setVerticalGroup(
            TotalVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TotalUsersLayout = new javax.swing.GroupLayout(TotalUsers);
        TotalUsers.setLayout(TotalUsersLayout);
        TotalUsersLayout.setHorizontalGroup(
            TotalUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TotalUsersLayout.setVerticalGroup(
            TotalUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AvailableVehiclesLayout = new javax.swing.GroupLayout(AvailableVehicles);
        AvailableVehicles.setLayout(AvailableVehiclesLayout);
        AvailableVehiclesLayout.setHorizontalGroup(
            AvailableVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        AvailableVehiclesLayout.setVerticalGroup(
            AvailableVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalVehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AvailableVehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RentedVehicles, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addComponent(OverdueAccounts))
                .addGap(46, 46, 46))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addComponent(TotalVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TotalUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AvailableVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addComponent(RentedVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OverdueAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(Dashboard);
        Dashboard.setBounds(60, 0, 850, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openAdminHome() {
        AdminHome adminHome = new AdminHome();
        adminHome.setVisible(true);
        adminHome.setLocationRelativeTo(null);
        this.setVisible(false);
    }
    
    private void openManageVehicles() {
        ManageVehicles manageVehicles = new ManageVehicles();
        manageVehicles.setVisible(true);
        manageVehicles.setLocationRelativeTo(null);
        this.setVisible(false);
    }
    
    private void openManageCustomers() {
        ManageCustomers manageCustomers = new ManageCustomers();
        manageCustomers.setVisible(true);
        manageCustomers.setLocationRelativeTo(null);
        this.setVisible(false);
    }
    
    private void openOverdueAccounts() {
        ManageOverdueAccounts manageOverdue = new ManageOverdueAccounts();
        manageOverdue.setVisible(true);
        manageOverdue.setLocationRelativeTo(null);
        this.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AvailableVehicles;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JButton DashboardButton;
    private javax.swing.JPanel NavigationMenu;
    private javax.swing.JScrollPane OverdueAccounts;
    private javax.swing.JButton OverdueAccountsButton;
    private javax.swing.JScrollPane RentedVehicles;
    private javax.swing.JPanel TotalUsers;
    private javax.swing.JPanel TotalVehicles;
    private javax.swing.JButton UsersButton;
    private javax.swing.JButton VehiclesButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    // End of variables declaration//GEN-END:variables
}
