
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author D21124318
 */
public class ManageCustomers extends javax.swing.JFrame {
    private SimpleDBConnect DBConnection = new SimpleDBConnect();
    
    private JTable usersTable;

    /**
     * Creates new form ManageCustomers
     */
    public ManageCustomers() {
        initComponents();
        setupActionListeners();
        populateComboBoxes();
        searchUsers();
    }
    
    // Method to set up action listeners for various buttons related to functionality
    private void setupActionListeners() {
        addActionListenerToButton(SearchUsers, this::searchUsers);
        //addActionListenerToButton(EditBtn, this::showEditVehicleDialog);
        //addActionListenerToButton(RemoveBtn, this::showRmvVehicleDialog);
        //addActionListenerToButton(AddVehicle, ManageVehicles.this::AddNewVehicle);
        //addActionListenerToButton(CancelAddVehicle, () -> addVehicleDialog.setVisible(false));
        //addActionListenerToButton(EditVehicle, ManageVehicles.this::EditVehicle);
        //addActionListenerToButton(CancelEditVehicle, () -> editVehicleDialog.setVisible(false));
        //addActionListenerToButton(OkRmvBtn, ManageVehicles.this::RemoveVehicle);
        //addActionListenerToButton(CancelRmvBtn, () -> rmvVehicleDialog.setVisible(false));
        
        
    }
    // Method to add an action listener to a button with a specific action
    private void addActionListenerToButton(JButton button, Runnable action) {
        button.addActionListener(e -> action.run());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        SurnameComboBox = new javax.swing.JComboBox<>();
        AccountStatusComboBox = new javax.swing.JComboBox<>();
        MobileComboBox = new javax.swing.JComboBox<>();
        AddressComboBox = new javax.swing.JComboBox<>();
        EmailComboBox = new javax.swing.JComboBox<>();
        SearchUsers = new javax.swing.JButton();
        ForenameComboBox = new javax.swing.JComboBox<>();
        AddUserBtn = new javax.swing.JButton();
        EditUsrBtn = new javax.swing.JButton();
        RemoveUsrBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        NavigationMenu = new javax.swing.JPanel();
        DashboardButton = new javax.swing.JButton();
        UsersButton = new javax.swing.JButton();
        VehiclesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(890, 500));
        getContentPane().setLayout(null);

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setMinimumSize(new java.awt.Dimension(804, 520));
        Dashboard.setName(""); // NOI18N
        Dashboard.setPreferredSize(new java.awt.Dimension(810, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(850, 98));

        SurnameComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SurnameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surname" }));

        AccountStatusComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AccountStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status" }));

        MobileComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MobileComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobile" }));

        AddressComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddressComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Address" }));

        EmailComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Email" }));

        SearchUsers.setText("Search");

        ForenameComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ForenameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Forename" }));

        AddUserBtn.setText("Add");

        EditUsrBtn.setText("Edit");

        RemoveUsrBtn.setText("Remove");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ForenameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddUserBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SurnameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditUsrBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveUsrBtn)
                    .addComponent(EmailComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddressComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MobileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ForenameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SurnameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MobileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddUserBtn)
                        .addComponent(EditUsrBtn)
                        .addComponent(RemoveUsrBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Dashboard);
        Dashboard.setBounds(60, 0, 810, 500);

        NavigationMenu.setBackground(new java.awt.Color(102, 102, 102));
        NavigationMenu.setPreferredSize(new java.awt.Dimension(60, 500));

        DashboardButton.setText("jButton1");

        UsersButton.setText("jButton1");

        VehiclesButton.setText("jButton1");

        javax.swing.GroupLayout NavigationMenuLayout = new javax.swing.GroupLayout(NavigationMenu);
        NavigationMenu.setLayout(NavigationMenuLayout);
        NavigationMenuLayout.setHorizontalGroup(
            NavigationMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(NavigationMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(DashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehiclesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        NavigationMenuLayout.setVerticalGroup(
            NavigationMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationMenuLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(DashboardButton)
                .addGap(96, 96, 96)
                .addComponent(UsersButton)
                .addGap(86, 86, 86)
                .addComponent(VehiclesButton)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        getContentPane().add(NavigationMenu);
        NavigationMenu.setBounds(0, 0, 60, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchUsers() {
        //SimpleDBConnect DBConnection = new SimpleDBConnect();
        String selectedForename = ForenameComboBox.getSelectedItem().toString();
        String selectedSurname = SurnameComboBox.getSelectedItem().toString();
        String selectedEmail = EmailComboBox.getSelectedItem().toString();
        String selectedAddress = AddressComboBox.getSelectedItem().toString();
        String selectedMobile = MobileComboBox.getSelectedItem().toString();
        String selectedStatus = AccountStatusComboBox.getSelectedItem().toString();

        // Call the searchCars function in DBConnection with selected options
        DefaultTableModel model = DBConnection.searchUsers(selectedForename, selectedSurname, selectedEmail, selectedAddress, selectedMobile, selectedStatus);
        // Create a new JTable with the populated model
        if(usersTable == null) {
            usersTable = new JTable(model);
            jScrollPane1.setViewportView(usersTable);
        } else {
            usersTable.setModel(model);
        }
        
        this.revalidate();
        this.repaint();
}
    
    private void populateComboBoxes() {
        SimpleDBConnect DBConnection = new SimpleDBConnect();
        DBConnection.populateComboBox(ForenameComboBox, "Forename", "Users");
        DBConnection.populateComboBox(SurnameComboBox, "Surname", "Users");
        DBConnection.populateComboBox(EmailComboBox, "Email", "Users");
        DBConnection.populateComboBox(AddressComboBox, "Address", "Users");
        DBConnection.populateComboBox(MobileComboBox, "Mobile", "Users");
        DBConnection.populateComboBox(AccountStatusComboBox, "AccountStatus", "Users");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCustomers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccountStatusComboBox;
    private javax.swing.JButton AddUserBtn;
    private javax.swing.JComboBox<String> AddressComboBox;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JButton DashboardButton;
    private javax.swing.JButton EditUsrBtn;
    private javax.swing.JComboBox<String> EmailComboBox;
    private javax.swing.JComboBox<String> ForenameComboBox;
    private javax.swing.JComboBox<String> MobileComboBox;
    private javax.swing.JPanel NavigationMenu;
    private javax.swing.JButton RemoveUsrBtn;
    private javax.swing.JButton SearchUsers;
    private javax.swing.JComboBox<String> SurnameComboBox;
    private javax.swing.JButton UsersButton;
    private javax.swing.JButton VehiclesButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
